---
title: "PCA -"
author: "Bibek Sapkota"
date: "2024-09-05"
output: html_document
---

# Creating a simple 2-dimention Dataset
```{r}
set.seed(1)

var_1 <- rnorm(50,50, sd =3)

var_2 <- .5*var_1 + rnorm(50, sd = sqrt(3))

data_set_1 <- data.frame(var_1, var_2)

head(data_set_1)
```


```{r}
library(ggplot2)

ggplot(data_set_1, aes(x = var_1, y = var_2))+
  geom_point(color= "blue", size = 2)+
  xlab("Variable 1")+
  ylab("Variable 2")+
  theme_classic()
```


# Center each variable
```{r}
library(dplyr)

data_set_1 <- data_set_1 %>% mutate(varc_1 = var_1 - mean(var_1), varc_2 = var_2 - mean(var_2))

head(data_set_1)
```

```{r}
ggplot(data_set_1, aes(x = varc_1, y = varc_2))+
  geom_point(color = "blue", size = 2) +
  geom_vline(xintercept = 0, size = .5) +
  geom_hline(yintercept = 0, size = .5) +
  theme_classic()
```

# Calculate the covariance matrix
```{r}
data_set_2 <- data_set_1 %>% 
  select(varc_1, varc_2) %>% 
  as.matrix()


cov_m <- (t(data_set_2) %*% data_set_2) / (nrow(data_set_2) - 1) 

cov_m
```

```{r}
cov(data_set_2)
```

```{r}
crossprod(data_set_2) / (nrow(data_set_2) - 1)
```


```{r}
cov_e <- eigen(cov_m)

# Eigenvectors
e_vec <- cov_e$vectors

# Eigenvalues
e_val <- cov_e$values
```


```{r}
# First eigenvector 
ev_1 <- e_vec[,1]

# First eigenvector slope
ev1_m <- ev_1[2] / ev_1[1]

# Second eigenvector 
ev_2 <- e_vec[,2]

# Second eigenvector slope
ev2_m <- ev_2[2] / ev_2[1]

# Scatter plot showing the span of both eigenvectors 
ggplot(data.frame(data_set_2), aes(x = varc_1, y = varc_2)) +
  geom_point(color = "blue", size = 2) +
  geom_vline(xintercept = 0, size = .5) +
  geom_hline(yintercept = 0, size = .5) +
  geom_abline(slope = ev1_m, color = "blue", size = 0.7) +
  geom_abline(slope = ev2_m, color = "red", size = 0.7) +
  theme_classic()
```

```{r}
# Multiply both eigenvectors 
ev_1 %*% ev_2
```

# Make a scree plot
```{r}
# Calculate the estimated variance for each eigenvalue
e_var <- e_val / (nrow(data_set_2) - 1)

# Data frame with variance percentages
var_per <- data.frame(
  PC  = c("PC1", "PC2"),
  PER = c(e_var) * 100 / sum(e_var) # Calculate the percentage
    )

# Scree plot 
ggplot(var_per, aes(x = PC, y = PER)) +
  geom_col(width = 0.5, color = "black") +
  xlab("Principal component") +
  ylab("Percentage of variation (%)") +
  theme_classic()
```

# Loading scores

```{r}
# Norm of the first eigenvector
norm(as.matrix(ev_1), "F")

# Norm of the second eigenvector
norm(as.matrix(ev_2), "F")
```

```{r}
# Data frame with both eigenvectors
loads <- data.frame(
  VAR   = c("var_1", "var_2"),
  PC1 = ev_1, # First eigenvecor
  PC2 = ev_2  # Second eigenvectors
)
loads
```

# Represent the data in lower dimensions


























